import { GRADE_LABEL_OPTIONS } from '@/constants/grades'

export const settingsConfig = {
  institutionType: 'school' as
    'school' | 'institute' | 'learning_center',

  admissionManagementEnabled: true,

  moduleLabel: {
    school: 'Admission Management',
    institute: 'Enrolment Management',
    learning_center: 'Enrolment Management',
  },

  newButtonLabel: {
    school: 'New Admission',
    institute: 'New Enrolment',
    learning_center: 'New Enrolment',
  },

  applicantLabel: {
    school: 'Applicant',
    institute: 'Student',
    learning_center: 'Student',
  },

  applyingForLabel: {
    school: 'Applying For',
    institute: 'Course / Program',
    learning_center: 'Program',
  },

  idPrefix: {
    school: 'AT',
    institute: 'EN',
    learning_center: 'EN',
  },

  finalStageLabel: {
    school: 'Admitted',
    institute: 'Enrolled',
    learning_center: 'Enrolled',
  },

  convertToStudentLabel: {
    school: 'Convert to Student',
    institute: 'Mark as Enrolled',
    learning_center: 'Mark as Enrolled',
  },

  pipeline: [
    {
      id: 'new',
      label: 'New',
      color: 'blue',
      bgClass: 'bg-blue-100',
      textClass: 'text-blue-800',
      borderClass: 'border-blue-200',
      dotClass: 'bg-blue-500',
      barClass: 'bg-blue-500',
      iconName: 'Sparkles',
      order: 1,
      isTerminal: false,
      requiresDocs: false,
      requiresPayment: false,
      count: 7,
    },
    {
      id: 'contacted',
      label: 'Contacted',
      color: 'amber',
      bgClass: 'bg-amber-100',
      textClass: 'text-amber-800',
      borderClass: 'border-amber-200',
      dotClass: 'bg-amber-500',
      barClass: 'bg-amber-500',
      iconName: 'Phone',
      order: 2,
      isTerminal: false,
      requiresDocs: false,
      requiresPayment: false,
      count: 4,
    },
    {
      id: 'application',
      label: 'Application',
      color: 'indigo',
      bgClass: 'bg-indigo-100',
      textClass: 'text-indigo-800',
      borderClass: 'border-indigo-200',
      dotClass: 'bg-indigo-500',
      barClass: 'bg-indigo-500',
      iconName: 'FileText',
      order: 3,
      isTerminal: false,
      requiresDocs: false,
      requiresPayment: false,
      count: 7,
    },
    {
      id: 'docs',
      label: 'Docs Uploaded',
      color: 'violet',
      bgClass: 'bg-violet-100',
      textClass: 'text-violet-800',
      borderClass: 'border-violet-200',
      dotClass: 'bg-violet-500',
      barClass: 'bg-violet-500',
      iconName: 'Upload',
      order: 4,
      isTerminal: false,
      requiresDocs: true,
      requiresPayment: false,
      count: 0,
    },
    {
      id: 'interview',
      label: 'Interview',
      color: 'cyan',
      bgClass: 'bg-cyan-100',
      textClass: 'text-cyan-800',
      borderClass: 'border-cyan-200',
      dotClass: 'bg-cyan-500',
      barClass: 'bg-cyan-500',
      iconName: 'Users',
      order: 5,
      isTerminal: false,
      requiresDocs: false,
      requiresPayment: false,
      count: 1,
    },
    {
      id: 'payment',
      label: 'Payment',
      color: 'orange',
      bgClass: 'bg-orange-100',
      textClass: 'text-orange-800',
      borderClass: 'border-orange-200',
      dotClass: 'bg-orange-500',
      barClass: 'bg-orange-500',
      iconName: 'CreditCard',
      order: 6,
      isTerminal: false,
      requiresDocs: false,
      requiresPayment: true,
      count: 6,
    },
    {
      id: 'admitted',
      label: 'Admitted',
      color: 'green',
      bgClass: 'bg-green-100',
      textClass: 'text-green-800',
      borderClass: 'border-green-200',
      dotClass: 'bg-green-500',
      barClass: 'bg-green-500',
      iconName: 'CheckCircle2',
      order: 7,
      isTerminal: true,
      requiresDocs: false,
      requiresPayment: false,
      count: 17,
    },
    {
      id: 'rejected',
      label: 'Rejected',
      color: 'red',
      bgClass: 'bg-red-100',
      textClass: 'text-red-800',
      borderClass: 'border-red-200',
      dotClass: 'bg-red-500',
      barClass: 'bg-red-500',
      iconName: 'XCircle',
      order: 8,
      isTerminal: true,
      requiresDocs: false,
      requiresPayment: false,
      count: 10,
    },
  ],

  formFields: [
    {
      id: 'dob',
      label: 'Date of Birth',
      type: 'date',
      required: true,
      section: 'applicant',
      order: 1,
    },
    {
      id: 'gender',
      label: 'Gender',
      type: 'select',
      required: true,
      section: 'applicant',
      order: 2,
      options: ['Male', 'Female', 'Other'],
    },
    {
      id: 'medium',
      label: 'Medium of Instruction',
      type: 'select',
      required: false,
      section: 'programme',
      order: 1,
      options: [
        'English', 'Tamil',
        'Hindi', 'Bilingual',
      ],
    },
    {
      id: 'prev_school',
      label: 'Previous School',
      type: 'text',
      required: false,
      section: 'education',
      order: 1,
    },
    {
      id: 'tc_number',
      label: 'TC Number',
      type: 'text',
      required: false,
      section: 'education',
      order: 2,
    },
    {
      id: 'sibling',
      label: 'Sibling in School',
      type: 'toggle',
      required: false,
      section: 'applicant',
      order: 3,
    },
  ],

  documents: [
    {
      id: 'birth_cert',
      label: 'Birth Certificate',
      required: true,
    },
    {
      id: 'photo',
      label: 'Passport Size Photo',
      required: true,
    },
    {
      id: 'tc',
      label: 'Transfer Certificate',
      required: false,
    },
    {
      id: 'report_card',
      label: 'Previous Year Report Card',
      required: false,
    },
    {
      id: 'aadhar_child',
      label: 'Aadhar Card (Child)',
      required: true,
    },
    {
      id: 'aadhar_parent',
      label: 'Aadhar Card (Parent)',
      required: false,
    },
    {
      id: 'address_proof',
      label: 'Address Proof',
      required: false,
    },
  ],

  grades: [...GRADE_LABEL_OPTIONS],

  courses: [
    'Bharatanatyam', 'Hip Hop',
    'Guitar - Beginner', 'Guitar - Advanced',
    'Keyboard', 'Vocals',
    'Yoga - Morning', 'Yoga - Evening',
    'Zumba', 'Karate', 'Swimming',
  ],

  academicYears: [
    'AY 2026-27 (Current)',
    'AY 2027-28 (Upcoming)',
    'AY 2025-26 (Previous)',
  ],

  academicYear: 'AY 2026-27',

  sources: [
    { id: 'vidhyaan', label: 'Vidhyaan',
      dot: 'bg-blue-500' },
    { id: 'walkin', label: 'Walk-in',
      dot: 'bg-teal-500' },
    { id: 'phone_enquiry',
      label: 'Phone Enquiry',
      dot: 'bg-purple-500' },
    { id: 'whatsapp', label: 'WhatsApp',
      dot: 'bg-green-500' },
    { id: 'school_website',
      label: 'School Website',
      dot: 'bg-slate-400' },
    { id: 'social_media',
      label: 'Social Media',
      dot: 'bg-pink-500' },
    { id: 'referral', label: 'Referral',
      dot: 'bg-amber-500' },
    { id: 'education_fair',
      label: 'Education Fair',
      dot: 'bg-indigo-500' },
    { id: 'newspaper_ad',
      label: 'Newspaper Ad',
      dot: 'bg-orange-500' },
    { id: 'google_ad', label: 'Google Ad',
      dot: 'bg-red-500' },
    { id: 'other', label: 'Other',
      dot: 'bg-slate-300' },
  ],
}

export type SettingsConfig = 
  typeof settingsConfig

export const config = settingsConfig
export const type = config.institutionType
export const pipeline = config.pipeline
