import React from 'react'
import { Document, Page, Text, View, StyleSheet, pdf } from '@react-pdf/renderer'
import type { Column, Kpi } from '@/lib/reports/queries/types'

// Generic report PDF: title, filter echo, KPI row, table. Used by the
// management-pack exports (fee summary, defaulter list, enrollment).

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 9, color: '#334155', fontFamily: 'Helvetica' },
  title: { fontSize: 16, fontWeight: 'bold', color: '#0f172a' },
  meta: { fontSize: 8, color: '#64748b', marginTop: 4 },
  kpiRow: { flexDirection: 'row', marginTop: 16, marginBottom: 16, gap: 8 },
  kpiBox: {
    flex: 1, borderWidth: 1, borderColor: '#e2e8f0', borderRadius: 4, padding: 8
  },
  kpiLabel: { fontSize: 7, color: '#64748b', textTransform: 'uppercase' },
  kpiValue: { fontSize: 13, fontWeight: 'bold', color: '#0f172a', marginTop: 2 },
  tableHeader: {
    flexDirection: 'row', borderBottomWidth: 1.5, borderBottomColor: '#cbd5e1',
    backgroundColor: '#f8fafc', paddingVertical: 5, paddingHorizontal: 4
  },
  tableRow: {
    flexDirection: 'row', borderBottomWidth: 0.5, borderBottomColor: '#e2e8f0',
    paddingVertical: 4, paddingHorizontal: 4
  },
  th: { fontSize: 7.5, fontWeight: 'bold', color: '#475569', textTransform: 'uppercase' },
  td: { fontSize: 8.5 },
  footer: {
    position: 'absolute', bottom: 24, left: 40, right: 40,
    fontSize: 7, color: '#94a3b8', textAlign: 'center'
  }
})

function formatValue(value: unknown, format?: Column['format']): string {
  if (value === null || value === undefined || value === '') return '—'
  if (value instanceof Date) return value.toLocaleDateString('en-IN')
  if (format === 'date') return new Date(String(value)).toLocaleDateString('en-IN')
  if (format === 'pct' && typeof value === 'number') return `${(value * 100).toFixed(1)}%`
  if (format === 'inr' && typeof value === 'number') {
    return `Rs ${Math.round(value).toLocaleString('en-IN')}`
  }
  return String(value)
}

export async function renderReportPdf(input: {
  title: string
  orgName: string
  filtersEcho: string
  kpis: Kpi[]
  columns: Column[]
  rows: Record<string, unknown>[]
}): Promise<Buffer> {
  const { title, orgName, filtersEcho, kpis, columns, rows } = input
  const doc = (
    <Document>
      <Page size="A4" style={styles.page} wrap>
        <Text style={styles.title}>{title}</Text>
        <Text style={styles.meta}>
          {orgName} · exported {new Date().toLocaleString('en-IN')} · {filtersEcho}
        </Text>

        <View style={styles.kpiRow}>
          {kpis.slice(0, 5).map(k => (
            <View key={k.key} style={styles.kpiBox}>
              <Text style={styles.kpiLabel}>{k.label}</Text>
              <Text style={styles.kpiValue}>{formatValue(k.value, k.format)}</Text>
            </View>
          ))}
        </View>

        <View style={styles.tableHeader} fixed>
          {columns.map(c => (
            <Text key={c.key} style={[styles.th, { flex: 1 }]}>
              {c.label}
            </Text>
          ))}
        </View>
        {rows.map((row, i) => (
          <View key={i} style={styles.tableRow} wrap={false}>
            {columns.map(c => (
              <Text key={c.key} style={[styles.td, { flex: 1 }]}>
                {formatValue(row[c.key], c.format)}
              </Text>
            ))}
          </View>
        ))}

        <Text style={styles.footer} fixed>
          Generated by Vidhyaan · {title}
        </Text>
      </Page>
    </Document>
  )
  // @react-pdf/renderer types toBuffer as ReadableStream; at runtime in Node
  // it resolves to a Buffer (same pattern as invoice-pdf).
  return pdf(doc).toBuffer() as unknown as Promise<Buffer>
}
