export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  OPERATIONS_ADMIN: 'OPERATIONS_ADMIN',
  SUPPORT_ADMIN: 'SUPPORT_ADMIN',
  ORG_ADMIN: 'ORG_ADMIN',
  BRANCH_ADMIN: 'BRANCH_ADMIN',
  COUNSELLOR: 'COUNSELLOR',
  RECEPTIONIST: 'RECEPTIONIST',
  ACCOUNTANT: 'ACCOUNTANT',
  TEACHER: 'TEACHER',
  PARENT: 'PARENT'
} as const

export const PLATFORM_ROLES = [
  ROLES.SUPER_ADMIN,
  ROLES.OPERATIONS_ADMIN,
  ROLES.SUPPORT_ADMIN
] as const

export const ORG_ROLES = [
  ROLES.ORG_ADMIN,
  ROLES.BRANCH_ADMIN,
  ROLES.COUNSELLOR,
  ROLES.RECEPTIONIST,
  ROLES.ACCOUNTANT,
  ROLES.TEACHER
] as const

export const CRM_ROLES = [
  ROLES.ORG_ADMIN,
  ROLES.BRANCH_ADMIN,
  ROLES.COUNSELLOR,
  ROLES.RECEPTIONIST
] as const
