import { Metadata } from 'next'
import CourseManagementBespokePage from '@/components/marketplace/CourseManagementBespokePage'

export const metadata: Metadata = {
  title: 'Course & Batch Management Software for Learning Centers & Coaching Institutes | Vidhyaan',
  description: 'Manage course catalogs, batch enrollments, and automatic recurring billing — built for learning centers, not a repurposed school ERP. Setup in under 15 minutes.',
  openGraph: {
    title: 'Course & Batch Management Software for Learning Centers & Coaching Institutes | Vidhyaan',
    description: 'Manage course catalogs, batch enrollments, and automatic recurring billing — built for learning centers, not a repurposed school ERP. Setup in under 15 minutes.',
    url: 'https://vidhyaan.com/products/course-management',
    images: [
      {
        url: 'https://vidhyaan.com/images/products/course-management-list-screenshot.png',
        width: 1024,
        height: 1024,
        alt: 'Vidhyaan Course catalog interface showing multiple course blocks including music, NEET coaching, and robotics with prices and schedules.',
      }
    ],
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Course & Batch Management Software for Learning Centers & Coaching Institutes | Vidhyaan',
    description: 'Manage course catalogs, batch enrollments, and automatic recurring billing — built for learning centers, not a repurposed school ERP. Setup in under 15 minutes.',
    images: ['https://vidhyaan.com/images/products/course-management-list-screenshot.png'],
  },
  alternates: {
    canonical: 'https://vidhyaan.com/products/course-management',
  }
}

export default function CourseManagementPage() {
  const faqs = [
    {
      q: "Can I set different billing frequencies for different courses?",
      a: "Yes — each course can be configured with its own frequency (one-time, monthly, quarterly, half-yearly, annual, or custom) independently of other courses."
    },
    {
      q: "Does enrolling a student automatically create an invoice?",
      a: "Yes — the first invoice generates automatically the moment a student is enrolled, and subsequent recurring invoices trigger automatically based on the frequency defined."
    },
    {
      q: "Do I have to build my course catalog from scratch?",
      a: "No — Vidhyaan seeds a starting catalog template based on your category (Music, Dance, Coaching, Art, and more), which you can edit, remove, or add to freely."
    },
    {
      q: "Does this work for schools too, or just learning centers?",
      a: "This is specific to Learning Centers and Coaching Centers. Schools and Junior Colleges typically use term-based Fee Management since school invoicing structures are different."
    },
    {
      q: "Can a student be enrolled in more than one course at a time?",
      a: "Yes. The system supports multiple concurrent enrollments per student, allowing them to participate in and be billed for separate courses simultaneously."
    },
    {
      q: "What happens to billing if a student pauses or cancels a course mid-cycle?",
      a: "When a student enrollment is set to 'PAUSED' or 'CANCELLED', the recurring billing cron will automatically skip it. Invoicing will only resume if the enrollment status is updated back to 'ACTIVE'."
    },
    {
      q: "Can I change a course's price after students are already enrolled?",
      a: "Yes. Changing a course price updates subsequent invoice amounts dynamically. All future invoices generated by the recurring billing cron will use the new price."
    },
    {
      q: "Is there a limit on how many courses I can create?",
      a: "No. Vidhyaan does not place any software limits on the number of courses or batches you can create. You can configure as many programs as your learning center requires."
    },
    {
      q: "Can I run a free trial class before enrolling a student formally?",
      a: "Yes — Vidhyaan supports public Trial Class Bookings for learning centers. Parents can book a trial class directly on your center's public profile, choosing their preferred date and batch schedule. You can manage these trial requests as leads inside your dashboard, and then enroll them with one click once they decide to join."
    }
  ]

  const jsonLd = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: faqs.map((item) => ({
      '@type': 'Question',
      name: item.q,
      acceptedAnswer: {
        '@type': 'Answer',
        text: item.a,
      },
    })),
  }

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      <CourseManagementBespokePage />
    </>
  )
}
