import subprocess
import os
import sys
from datetime import datetime

project_root = "/Users/vimaldas/Projects/VidhyaanCRM"
claude_path = os.path.join(project_root, "CLAUDE.md")

def run_cmd(cmd, cwd=project_root):
    try:
        res = subprocess.run(cmd, shell=True, cwd=cwd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
        return res.returncode, res.stdout, res.stderr
    except Exception as e:
        return -1, "", str(e)

def get_stats():
    stats = {}
    # Count page lines
    page_path = os.path.join(project_root, "src/app/(crm)/dashboard/page.tsx")
    if os.path.exists(page_path):
        with open(page_path, "r") as f:
            stats["page_lines"] = len(f.readlines())
            stats["page_size_kb"] = round(os.path.getsize(page_path) / 1024, 1)
    else:
        stats["page_lines"] = 0
        stats["page_size_kb"] = 0
    return stats

def main():
    print("Verifying build status...")
    code, stdout, stderr = run_cmd("npm run build")
    
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    stats = get_stats()
    
    status_str = f"## 🤖 Autogenerated Project Status\n"
    status_str += f"*   **Last Run Timestamp**: `{timestamp}`\n"
    
    if code == 0:
        status_str += f"*   **Build Compilation**: `✓ Success` (Ready to deploy)\n"
    else:
        status_str += f"*   **Build Compilation**: `✗ Failed` (Exit code: {code})\n"
        status_str += f"    *Error Log Output*:\n    ```\n    {stderr[:200]}\n    ```\n"
        
    status_str += f"*   **Code Statistics**:\n"
    status_str += f"    *   [Dashboard (page.tsx)](file://{project_root}/src/app/(crm)/dashboard/page.tsx): `{stats['page_lines']} lines` (`{stats['page_size_kb']} KB`)\n"
    status_str += f"    *   [Style Guide (globals.css)](file://{project_root}/src/app/globals.css): `{round(os.path.getsize(os.path.join(project_root, 'src/app/globals.css')) / 1024, 1)} KB`\n"

    # Read current CLAUDE.md
    if os.path.exists(claude_path):
        with open(claude_path, "r") as f:
            content = f.read()
    else:
        content = ""

    start_marker = "<!-- BUILD_STATUS_START -->"
    end_marker = "<!-- BUILD_STATUS_END -->"
    
    if start_marker in content and end_marker in content:
        start_idx = content.find(start_marker) + len(start_marker)
        end_idx = content.find(end_marker)
        new_content = content[:start_idx] + "\n" + status_str + "\n" + content[end_idx:]
    else:
        # Append to the end
        new_content = content + f"\n\n{start_marker}\n{status_str}\n{end_marker}\n"

    with open(claude_path, "w") as f:
        f.write(new_content)

    print(f"CLAUDE.md context updated successfully at {timestamp}.")
    sys.exit(code)

if __name__ == "__main__":
    main()
